### PR TITLE
cuisine is lowercase

### PR DESCRIPTION
**Pull request by matkoniecz**
this fixes https://josm.openstreetmap.de/ticket/23587

is it intentional that issues are not enabled on this repository?

### CODE REVIEW

**Comment by matkoniecz** [comment]
@depth221 - maybe you missed this one?

**Comment by depth221** [comment]
I didn't get the notification for this PR. I'm sorry.

**Comment by matkoniecz** [comment]
I guess you can watchlist repository to get such notifications.

**Comment by matkoniecz** [comment]
And thanks for the review!

**Pull request merged**
